In [9]:
import numpy as np

In [10]:
arr = np.arange(5)

In [11]:
arr

array([0, 1, 2, 3, 4])

In [14]:
np.save('myarray',arr)

In [15]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [17]:
arr1 = np.load('myarray.npy')

In [18]:
arr1

array([0, 1, 2, 3, 4])

In [22]:
arr2 = arr

In [23]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.savez('ziparray.npz',x=arr1,y=arr2)

In [25]:
archieve_array = np.load('ziparray.npz')

In [26]:
archieve_array['x']

array([0, 1, 2, 3, 4])

In [27]:
archieve_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.savetxt('mytextarray.txt',arr,delimiter=',')

In [33]:
arr = np.loadtxt('mytextarray.txt',delimiter=',')

In [34]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])